In [1]:
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
archivo_Torre2 = "../data/001_raw/002_Torre2.csv"
torre = pd.read_csv(archivo_Torre2, index_col=0, parse_dates=True)

archivo_mayo = "../data/002_intermediate/29_may_clean.parquet"
may = pd.read_parquet(archivo_mayo)
may.index

DatetimeIndex(['2026-05-25 13:53:37', '2026-05-25 13:54:37',
               '2026-05-25 13:55:37', '2026-05-25 13:56:37',
               '2026-05-25 13:57:37', '2026-05-25 13:58:37',
               '2026-05-25 13:59:37', '2026-05-25 14:00:37',
               '2026-05-25 14:01:37', '2026-05-25 14:02:37',
               ...
               '2026-05-29 08:53:37', '2026-05-29 08:54:37',
               '2026-05-29 08:55:37', '2026-05-29 08:56:37',
               '2026-05-29 08:57:37', '2026-05-29 08:58:37',
               '2026-05-29 08:59:37', '2026-05-29 09:00:37',
               '2026-05-29 09:01:37', '2026-05-29 09:02:37'],
              dtype='datetime64[us]', name='Sello de tiempo', length=5470, freq=None)

In [3]:

torre.index = pd.to_datetime(torre.index, format="mixed").tz_localize(None)
torre

,T03,T04,T05,T06,T07,T08,T01,T02
timestamp,,,,,,,,
2026-05-27 00:00:14.504,24.51,24.37,24.36,24.11,23.83,23.70,24.79,24.95
2026-05-27 00:00:34.409,24.56,24.42,24.33,24.08,23.86,23.72,24.74,24.88
2026-05-27 00:00:54.314,24.57,24.38,24.32,23.95,23.78,23.54,24.76,24.88
2026-05-27 00:01:14.222,24.44,24.17,24.18,23.92,23.62,23.52,24.72,24.91
2026-05-27 00:01:34.126,24.33,24.10,24.07,23.88,23.60,23.43,24.68,24.78
...,...,...,...,...,...,...,...,...
2026-06-02 11:18:09.096,23.84,23.92,23.68,23.66,23.73,23.80,23.99,23.99
2026-06-02 11:18:28.993,23.72,23.75,23.46,23.45,23.55,23.54,23.93,23.91
2026-06-02 11:18:48.893,23.63,23.60,23.42,23.42,23.48,23.36,23.90,23.91
2026-06-02 11:19:08.792,23.60,23.67,23.46,23.40,23.50,23.50,23.87,23.80
2026-06-02 11:19:28.692,23.55,23.51,23.49,23.31,23.39,23.34,23.90,23.79

In [4]:
torre_min = torre.copy()
may_min = may.copy()

torre_min.index = torre_min.index.floor("min")
may_min.index = may_min.index.floor("min")


torre_min = torre_min.groupby(level=0).mean()

concatenado = pd.concat(
    [torre_min, may_min],
    axis=1,
    join="inner"
)

concatenado

,T03,T04,T05,T06,T07,T08,T01,T02,Temp,BH,PC,% HR,CO2
2026-05-27 00:00:00,24.546667,24.390000,24.336667,24.046667,23.823333,23.653333,24.763333,24.903333,24.4,18.3,15.6,58.3,408
2026-05-27 00:01:00,24.346667,24.126667,24.100000,23.870000,23.580000,23.476667,24.676667,24.830000,24.0,18.2,15.6,59.4,403
2026-05-27 00:02:00,24.180000,23.996667,24.010000,23.820000,23.526667,23.536667,24.630000,24.693333,24.1,18.2,15.6,59.3,414
2026-05-27 00:03:00,24.233333,24.080000,24.026667,23.843333,23.580000,23.546667,24.616667,24.693333,24.2,18.2,15.6,59.1,410
2026-05-27 00:04:00,24.373333,24.176667,24.123333,23.933333,23.736667,23.683333,24.730000,24.783333,24.3,18.3,15.6,58.7,424
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2026-05-29 08:58:00,25.483333,25.543333,25.303333,25.170000,25.246667,25.116667,25.643333,25.566667,25.8,17.3,13.2,45.8,418
2026-05-29 08:59:00,25.133333,25.226667,24.970000,24.896667,25.026667,24.853333,25.496667,25.336667,25.3,17.1,13.0,46.7,409
2026-05-29 09:00:00,25.240000,25.313333,25.013333,24.916667,25.013333,24.953333,25.466667,25.380000,25.8,17.5,13.4,46.4,414
2026-05-29 09:01:00,25.203333,25.273333,25.066667,24.863333,24.986667,24.886667,25.456667,25.420000,25.4,17.2,13.2,47.0,408
2026-05-29 09:02:00,25.310000,25.423333,25.226667,25.100000,25.126667,25.040000,25.516667,25.413333,25.7,17.3,13.2,46.2,428

In [5]:
may_torre = concatenado.to_parquet("../data/002_intermediate/may_torre.parquet")